### ISSUE TITLE
iptables 1.4.20 comp.

### ISSUE THREAD

**Issue by ghost** [T0aD/php_iptables#1]
//closed

**Comment by T0aD** [comment]
Im quoting your email since you deleted this ticket and its content altogether:

is it possible to add a support for the latest iptables version ? And also is it possible to add some new features like ip6 support or functions as

iptc_insert_entry
iptc_replace_entry
iptc_append_entry
iptc_check_entry
iptc_delete_entry
iptc_delete_num_entry
iptc_flush_entries

which are already in the latest version.

And for me, the parts iptc_append_entry and iptc_check_entry are very important. It is very much appreciated, if you can do something.
